### ISSUE TITLE
Case-sensitive dictionary access does not allow testing with twitch-cli

### ISSUE THREAD

**Issue by mkosler** [TwitchLib/TwitchLib.EventSub.Webhooks#1]
I started to work on an application that will use Twitch EventSub, and Twitch provides a handy tool called the [twitch-cli](https://dev.twitch.tv/docs/cli) to simulate EventSub triggers. However, when twitch-cli creates the necessary headers for EventSub event, it creates them in all lowercase:

![image](https://user-images.githubusercontent.com/1159095/142796938-4d02e19b-7454-412e-a211-f60d3e3db9e6.png)

This causes failures even within the example application in this repository, notably always triggering a Missing_Header error.

Following the Twitch EventSub docs, [they recommend always converting any check to lower case prior to checking the headers.](https://dev.twitch.tv/docs/eventsub/handling-webhook-events#list-of-request-headers)

**Comment by Syzuna** [comment]
Hey,
thanks for reporting that.
I tested the current implementation with the cli myself so that comes as a surprise to me. 
Will look into it

**Comment by Syzuna** [comment]
Version 1.1.1 should fix that and will now use OrdinalIgnoreCase for the dictionary key comparision
