### ISSUE TITLE
Exception with HypeTrainBegin event

### ISSUE THREAD

**Issue by NephChevsky** [TwitchLib/TwitchLib.EventSub.Webhooks#2]
It seems the Twitchlib.EventSub module doesn't work with the channel.hype_train.begin event

It crashes on the LastContribution object which expects an array of HypeTrainContribution
But it's only a single element

![image](https://user-images.githubusercontent.com/20585316/187089797-64968a39-96c4-46c9-8724-7d6849f28e27.png)

[Error] WebApp.Services.EventSubService: Reason: Application_Error - Message: The JSON value could not be converted to TwitchLib.EventSub.Webhooks.Core.Models.HypeTrain.HypeTrainContribution[]. Path: $.event.last_contribution | LineNumber: 0 | BytePositionInLine: 738.

**Comment by Syzuna** [comment]
I will make a release with that fix soonish.
if I am at it I might just as well add the new charity beta subscription type before doing a release

**Comment by Syzuna** [comment]
Version 1.3.0 should be available in nuget shorty.
<https://www.nuget.org/packages/TwitchLib.EventSub.Webhooks/1.3.0>
